### PR TITLE
Semicolon is optional for use and include

### PR DESCRIPTION
**Pull request by Lenbok**
I don't know rust / cargo etc, but it looks to me like this is the change needed :-).

(If you could tell me how I would build this updated version and install locally so that `openscad-language-server` knows how to use it, I'd be grateful)

### CODE REVIEW

**Comment by bollian** [comment]
Most development of tree-sitter parsers is done using nodejs and npm. You can find the instructions on how to set that up for yourself here: https://tree-sitter.github.io/tree-sitter/creating-parsers

The tldr for you would be:
1. Install npm (there are many ways, pick your poison)
2. From the source directory, run `npm install` to get all the dependencies
3. `export PATH=$PATH:./node_modules/.bin` to get the `tree-sitter` CLI command
4. `tree-sitter generate` to build your changes
5. `tree-sitter test` to make sure you didn't unintentionally break any of the existing test cases
6. Add a new test case covering your change (instructions here: https://tree-sitter.github.io/tree-sitter/creating-parsers#command-test)

The rust / cargo stuff only provide bindings to the underlying parser written in C, so you probably don't need it. I'll only check that the rust bindings build before I merge the branch.

Currently, when I run `tree-sitter generate` on your branch, I get the following error:
```
Unresolved conflict for symbol sequence:

  'use'  include_path  •  ';'  …

Possible interpretations:

  1:  (include_statement  'use'  include_path  •  ';')
  2:  (include_statement  'use'  include_path)  •  ';'  …

Possible resolutions:

  1:  Specify a left or right associativity in `include_statement`
  2:  Add a conflict for these rules: `include_statement`
```
So there's an ambiguity in the parser you need to fix before I can merge this.

**Comment by Lenbok** [comment]
@bollian Thanks for the instructions! I've updated the PR to specify an associativity and test the new functionality. npm changed the `package.json`, it doesn't seem wholly related, so I put that into a final commit that can be dropped if required.

**Comment by bollian** [comment]
I'm merging this without the changes to package.json.

If you don't mind me asking @Lenbok, what are you using this for?

**Comment by Lenbok** [comment]
Thanks @bollian ! I am using the openscad language server by @dzhu. I am also interested in seeing if structural editing is possible, eg via https://github.com/ethan-leba/tree-edit

**Pull request closed without merging**
