### PR TITLE
Extend the grammar a bit (list comprehensions and trailing commas)

### PR DESCRIPTION
**Pull request by dzhu**
Just a few tweaks to accept more things that OpenSCAD 2021.01 accepts.

## Trailing commas

For some reason, OpenSCAD allows trailing commas in lists and function/module declarations (even with zero elements/parameters!) but not in function/module calls.

## List comprehensions

The brackets are not actually an inherent part of list comprehensions; there can be multiple comprehensions within one list or nested `for` clauses. Accordingly, list comprehensions should instead be treated as list cells rather than top-level expressions.

Examples:
- `[for (i = [1, 2]) i, for (j = [3, 4]) j]` == `[1, 2, 3, 4]`
- `[for (i = [1, 2]) for (j = [3, 4]) i * j]` == `[3, 4, 6, 8]`

The addition of a precedence on `if_clause` is necessary to satisfy the grammar generator; I must confess that I'm not sure why or whether it should be right or left.

----

p.s. Thanks for putting this grammar together! I was just about to embark on doing the same thing myself when I came across this repo, already ready to go. It's been very helpful!

### CODE REVIEW

**Comment by bollian** [comment]
Awesome, thanks for the PR! Before merging I'm going to test it on my own machine and look into that `if_clause` precedence issue. The choice between left or right can be really important so I wanna make sure we get it ~right~ correct.

If you don't mind me asking, what are you using this for? I ask because I've yet to get syntax highlighting working, and I've actually got a standing issue (https://github.com/tree-sitter/tree-sitter/issues/1324) on the tree-sitter main repo for it. If you need syntax highlighting, it would be great if you gave it a try and let me know how it goes.

**Comment by bollian** [comment]
Looks like your choice of right-precedence was correct. The precedence is needed to resolve this situation:

```
if_for_ifelse = [for (x = 0) if (x < 0) for (y = 2) if (y == 2) y else x];
```

In the above example, which if clause is the `else` associated with? After some testing with OpenSCAD, it appears the answer is the right-most if clause, hence right precedence is the correct choice. You can essentially read the above example as

```
if_for_ifelse = [for (x = 0) if (x < 0) for (y = 2) (if (y == 2) y else x)];
```

However, this does reveal another problem. What if we wanted that else to be associated with the left-most if clause? OpenSCAD allows you to solve that problem by grouping if clauses using parentheses:

```
if_for_ifelse = [for (x = 0) if (x < 0) for (y = 2) (if (y == 2) y) else x];
```

The parser currently doesn't handle this syntax, and I'm sure there are other corner cases I haven't thought of. I'm gonna merge this PR anyway and create issues to track the lack of grouping support.

**Comment by dzhu** [comment]
Thanks for the quick response and thorough verification! Yeah, I feel like that line with the parenthesized `if` is getting into pretty obscure bits of the language.

I'm working on an [LSP](https://microsoft.github.io/language-server-protocol/) server for OpenSCAD. Syntax highlighting could come into play (there's a feature for clients to take highlighting information from the server); I wasn't planning for it to be a high priority, though I could try it out at some point if that would be helpful.

I'm just about ready to release the initial version of my thing, but I wanted to ask first (I guess this would most properly be a separate issue, but while we're here...): could you update `Cargo.toml` to allow `tree-sitter` 0.20 (and publish a new version to crates.io)? I've been using 0.20 locally for a useful new method that it provides (`TreeCursor::goto_first_child_for_byte`).

**Comment by bollian** [comment]
I will absolutely bump to 0.20 and make a new release. The only reason I had it at 0.19.5 was because 0.20 wasn't released on crates.io yet.

It's great to hear that you're making a language server. That was actually my initial reason for making this parser before life got in the way and I had to move on to other things. I look forward to seeing you publish!

**Comment by bollian** [comment]
I've just published an updated version using tree-sitter 0.20.

As for syntax highlighting, I was able to clear the blocker I had before, but now I'm encountering a bug in tree-sitter that's preventing highlighting from working. Apparently there's a fix in master, but there's no rush for you to go and test it.

**Comment by dzhu** [comment]
Great, thanks for the update! I've published the server at https://github.com/dzhu/openscad-language-server; give it a spin when you get a chance. And I'll probably be back here with another issue or PR before too long. :slightly_smiling_face:

**Pull request merged**
