### PR TITLE
feat: extend highlights and locals and set indents

### PR DESCRIPTION
**Pull request by wilriker**
I extended the `highlight.scm` with builtins, filled `locals.scm` and added `indents.scm`.

These are most likely not complete this way but they are at least more complete than before. ;-)

### CODE REVIEW

**Comment by bollian** [comment]
So I'm still going to spend a little more time working on this, but there are definitely some changes here that don't work well with my preferred editor (neovim). Can I ask what you're using to test this?

**Comment by wilriker** [comment]
I use it with `neovim` (nightly) and `nvim-treesitter`. ;-) What isn't working for you as expected?

**Comment by bollian** [comment]
The string highlighting is the only thing I've found that doesn't work, both for string literals and include paths. I'll probably trust you on the locals and indent queries, as I don't currently use those features.

**Comment by wilriker** [comment]
I rechecked and found that I actually had a mistake for both of these. Should now be fixed.

**Comment by bollian** [comment]
Looks good. Thanks for the changes!

**Pull request merged**
