### PR TITLE
'each' keyword should be followed by a list or an identifier of list.

### PR DESCRIPTION
**Pull request by Leathong**

### CODE REVIEW

**Comment by Leathong** [comment]
https://github.com/Leathong/openscad-support-vscode/issues/8

**Comment by Leathong** [comment]
@bollian hello ?

**Comment by bollian** [comment]
Thank you for the ping, I fell behind on email :)

I'll take a look at this later today.

**Comment by bollian** [comment]
Having only looked at this from my phone, I have two concerns:
- I'm fairly certain 'each' can be used with things other than lists, it just only expands to a single element. Why was the previous version insufficient?
- I want 'assert' to be included in the AST output and not ignored as a comment because it could be useful for language servers or alternative OpenSCAD implementations

**Comment by bollian** [comment]
`each` expansion accepts a lot more than just identifiers and lists. As far as I can tell, any expression (bool, number, string, list, function, undef, variable, etc.) can be used, as well as list comprehensions. There may yet be more cases I've not caught, but it should be easy to add those as they come up. I've added support for this in 67623a7e0367df39579e5d541273da5f7c71e639 as well as a unit test you can read for examples.

The `assert` issue is a bit more tricky, since it's doing effectively the same thing as what this parser calls a "transform chain" (`translate([1, 2, 3]) cube()`), but can be used in both those transform chains _and_ expressions that return values. Up until now, I'd never supported doing this sort of thing in the context of an expression. I would like to have the same `assert` parser regardless of whether or not it's in a statement or an expression, but it's also probably important for whatever is on the right side of the `assert` to know the context of the `assert` since this seems important for name resolution. So, `assert`s in a statement can only be followed by a statement, and `assert`s in an expression can only be followed by an expression. Since this is a bit challenging, I'll only be able to try and fix it this weekend.

@Leathong you might be able to get it done before me. I expect unit tests if you do :).

**Comment by Leathong** [comment]
> `each` expansion accepts a lot more than just identifiers and lists.

Yes, any expression that produces a list can be accepted by it.

**Comment by Leathong** [comment]
“Assert()” can be inserted to any position, just like comments , I have no idea how to parse it now. The comment is included

**Pull request closed without merging**
